spring:
  application:
    name: qcscribe-service
  ai:
    openai:
      api-key: <api key>
      chat:
        options:
          model: gpt-4
    vectorstore:
      qdrant:
        host: <qdrant host>
        port: <qdrant grpc port>
        collection-name: <collection name>
        api-key: <qdrant api key>
        use-tls: true
qcscribe:
  search:
    topK: 10
    threshold: 0.0