spring:
  application:
    name: qcscribe-service
  ai:
    openai:
      api-key: <openai api key>
    vectorstore:
      qdrant:
        host: <qdrant host>
        port: <qdrant grpc port>
        collection-name: <collection name>
        api-key: <qdrant api key>
        use-tls: true
qcscribe:
  search:
    topK: 10
    threshold: 0